site_name: Breaker Pannel Label Maker

theme:
  name: "material"

plugins:
  - mkdocstrings
  - search
  - codeinclude:
      title_mode: pymdownx.tabbed 

markdown_extensions:
    - attr_list
    - mkdocs-click

use_directory_urls: false

nav:
  - index.md
  # - tutorials.md
  # - explanation.md
  - API Reference: reference.md
  - cli.md

repo_url: https://github.com/3ltreilly/breaker_panel_labels
