site_name: Breaker Pannel Label Maker

theme:
  name: "material"

plugins:
  - mkdocstrings
  - search

use_directory_urls: false

nav:
  - index.md
  # - tutorials.md
  # - explanation.md
  - API Reference: reference.md

repo_url: https://github.com/3ltreilly/breaker_panel_labels
